In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("final_data - final_data.csv")

In [3]:
pd.set_option('display.max_columns' , None)

In [4]:
df.head()

,Facing,Price,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Transition_Type,Furnishing,Address,Floor Number,Per Sqft,Main Description,Additional Details,Extra Room,Nearby Locations,Features,AreaType,Given Area,Property Type,Dealer,Society Name
0,West,61 Lac,2 Bedrooms,2 Bathrooms,1 Balcony,1 to 5 Year Old,"Others,Park/Garden,Main Road",NaN,Resale,Unfurnished,"0001, Sector 90 Gurgaon, Gurgaon, Haryana",14th of 14 Floors,"@ 8,840 per sq.ft.","Green court society, which is bang on 60-Meter...",NaN,Store Room,"['Baba Kanala Chowk', 'Pataudi Rd', 'Gurukul P...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",Super Built-up Area,690 sqft,2 BHK Flat in Sector 90 Gurgaon,Ashiana homes,Green Court
1,South,70 Lac,2 Bedrooms,2 Bathrooms,1 Balcony,1 to 5 Year Old,"Others,Park/Garden,Main Road",NaN,Resale,Unfurnished,"0001, Sector 90 Gurgaon, Gurgaon, Haryana",8th of 14 Floors,"@ 10,144 per sq.ft.","Green court society, which is bang on 60-Meter...",Additional details: Piped gas facility is avai...,Store Room,"['Baba Kanala Chowk', 'Pataudi Rd', 'Gurukul P...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",Super Built-up Area,690 sqft,2 BHK Flat in Sector 90 Gurgaon,Ashiana homes,Green Court
2,North-East,71 Lac,2 Bedrooms,2 Bathrooms,1 Balcony,1 to 5 Year Old,"Park/Garden,Club,Main Road",Yes,Resale,Semifurnished,"Sector 70A Gurgaon, Gurgaon, Haryana",9th of 17 Floors,"@ 8,492 per sq.ft.",Available for sale 2 bhk semi furnished in pyr...,NaN,No,"['Airia Mall', 'Sohna Road', ""St. Angel's Glob...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",Super Built-up Area,836 sqft,2 BHK Flat in Sector 70A Gurgaon,dbn group,Pyramid Urban Homes
3,East,1.55 Cr,2 Bedrooms,2 Bathrooms,2 Balconies,0 to 1 Year Old,"Pool,Park/Garden,Club,Main Road",Yes,Resale,Semifurnished,"Sector 68 Gurgaon, Gurgaon, Haryana",9th of 20 Floors,"@ 12,301 per sq.ft.",Looking for a 2 bhk property for sale in gurga...,NaN,No,"['Airia Mall', 'Southern Peripheral Road', 'So...","['Power Back-up', 'Security / Fire Alarm', 'In...",Super Built-up Area,"1,260 sqft",2 BHK Flat in Sector 68 Gurgaon,Shree Shyam Properties,M3M The Marina
4,North,1.3 Cr,2 Bedrooms,2 Bathrooms,3+ Balconies,1 to 5 Year Old,"Pool,Club,Park/Garden",Yes,Resale,NaN,"101, Sector 107 Gurgaon, Gurgaon, Haryana",1st of 14 Floors,"@ 9,516 per sq.ft.",This 2 bhk apartment is available for sale in ...,NaN,No,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...","['Power Back-up', 'Intercom Facility', 'Lift(s...",Super Built-up Area,"1,366 sqft",2 BHK Flat in Sector 107 Gurgaon,JBM Buildtech Pvt Ltd,M3M Woodshire

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13998 entries, 0 to 13997
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Facing              12950 non-null  object
 1   Price               13965 non-null  object
 2   No_Bedroom          13965 non-null  object
 3   No_Bathroom         13964 non-null  object
 4   No_Balcony          13965 non-null  object
 5   Age                 13961 non-null  object
 6   Overlooking         13095 non-null  object
 7   Corner_Property     9151 non-null   object
 8   Transition_Type     13965 non-null  object
 9   Furnishing          13505 non-null  object
 10  Address             13947 non-null  object
 11  Floor Number        13965 non-null  object
 12  Per Sqft            13963 non-null  object
 13  Main Description    13995 non-null  object
 14  Additional Details  337 non-null    object
 15  Extra Room          13998 non-null  object
 16  Nearby Locations    13998 non-null  object
 17  Features            13998 non-null  object
 18  AreaType            13998 non-null  object
 19  Given Area          13998 non-null  object
 20  Property Type       13998 non-null  object
 21  Dealer              13998 non-null  object
 22  Society Name        13998 non-null  object
dtypes: object(23)
memory usage: 2.5+ MB

In [6]:
df.duplicated().sum()

np.int64(1519)

In [7]:
df.drop_duplicates(inplace = True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12479 entries, 0 to 13994
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Facing              11546 non-null  object
 1   Price               12447 non-null  object
 2   No_Bedroom          12447 non-null  object
 3   No_Bathroom         12446 non-null  object
 4   No_Balcony          12447 non-null  object
 5   Age                 12443 non-null  object
 6   Overlooking         11673 non-null  object
 7   Corner_Property     8207 non-null   object
 8   Transition_Type     12447 non-null  object
 9   Furnishing          12031 non-null  object
 10  Address             12430 non-null  object
 11  Floor Number        12447 non-null  object
 12  Per Sqft            12445 non-null  object
 13  Main Description    12476 non-null  object
 14  Additional Details  320 non-null    object
 15  Extra Room          12479 non-null  object
 16  Nearby Locations    12479 non-null  object
 17  Features            12479 non-null  object
 18  AreaType            12479 non-null  object
 19  Given Area          12479 non-null  object
 20  Property Type       12479 non-null  object
 21  Dealer              12479 non-null  object
 22  Society Name        12479 non-null  object
dtypes: object(23)
memory usage: 2.3+ MB

In [9]:
df.isna().sum()

Facing                  933
Price                    32
No_Bedroom               32
No_Bathroom              33
No_Balcony               32
Age                      36
Overlooking             806
Corner_Property        4272
Transition_Type          32
Furnishing              448
Address                  49
Floor Number             32
Per Sqft                 34
Main Description          3
Additional Details    12159
Extra Room                0
Nearby Locations          0
Features                  0
AreaType                  0
Given Area                0
Property Type             0
Dealer                    0
Society Name              0
dtype: int64

In [10]:
df.drop(columns = [ 'Additional Details' ] , inplace=True)

In [11]:
df.drop(columns = [ 'Transition_Type' ] , inplace=True)

In [12]:
df.shape

(12479, 21)

In [13]:
df.sample(6)

,Facing,Price,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Floor Number,Per Sqft,Main Description,Extra Room,Nearby Locations,Features,AreaType,Given Area,Property Type,Dealer,Society Name
3720,West,6.25 Cr,4 Bedrooms,4 Bathrooms,3 Balconies,10+ Year Old,Park/Garden,NaN,Semifurnished,"Higher Floor, DLF Phase 5, Gurgaon, Haryana",16th of 19 Floors,"@ 26,205 per sq.ft.",This lovely 4 bhk apartment/flat in dlf phase ...,Servant Room,"['Sector 53-54', 'Sahara Mall', 'Golf Course R...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",Super Built-up Area,"2,385 sqft","4 BHK Flat in DLF Phase 5, Gurgaon",Indus Estate,DLF Trinity Towers
4818,North,3.18 Cr,3 Bedrooms,4 Bathrooms,3+ Balconies,5 to 10 Year Old,"Park/Garden,Main Road",NaN,Semifurnished,"Sector 57 Gurgaon, Gurgaon, Haryana",8th of 18 Floors,"@ 13,385 per sq.ft.",Located in the popular residential address of ...,Servant Room,"['Presidium School Gurgoan', 'Manav Rachna Sch...","['Security / Fire Alarm', 'Intercom Facility',...",Super Built-up Area,"2,428 sqft",3 BHK Flat in Sector 57 Gurgaon,Investors Junction,BPTP Freedom Park Life
9270,North-East,6 Cr,3 Bedrooms,4 Bathrooms,3+ Balconies,10+ Year Old,"Others,Park/Garden",Yes,Semifurnished,"D 4, Sector 53 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,"@ 20,725 per sq.ft.",Located in the popular residential address of ...,Servant Room,"['Sector 53-54 Metro Station', 'Sahara Mall', ...","['Centrally Air Conditioned', 'Water purifier'...",Super Built-up Area,"2,895 sqft",3 BHK Flat in Sector 53 Gurgaon,Imperial Properties,Parsvnath Exotica
2088,North-East,1.3 Cr,3 Bedrooms,3 Bathrooms,3+ Balconies,1 to 5 Year Old,"Park/Garden,Main Road,Club,Pool,Others,Sea facing",NaN,Unfurnished,"K400, Sector 37D Gurgaon, Gurgaon, Haryana",5th of 19 Floors,"@ 7,344 per sq.ft.","Expressway facing balcony, a 3bhk flat in sect...",Pooja Room,"['The Esplanade Mall', 'Dwarka Express', 'Euro...","['Centrally Air Conditioned', 'Water purifier'...",Super Built-up Area,"1,770 sqft",3 BHK Flat in Sector 37D Gurgaon,Investors Junction,Ramprastha The Edge Towers
3546,North,1.91 Cr,3 Bedrooms,3 Bathrooms,2 Balconies,1 to 5 Year Old,"Park/Garden,Club,Pool",NaN,Unfurnished,"Middle Floor Tower B, Sector 90 Gurgaon, Gurga...",11st of 30 Floors,"@ 9,936 per sq.ft.",Dlf regal garden sector 90 north-East facing 3...,Others,"['SS Omnia, Sector 86', 'Numberdar market, IMT...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",Super Built-up Area,"1,726 sqft",3 BHK Flat in Sector 90 Gurgaon,Akay Estate,DLF Regal Gardens
5153,North-East,2.23 Cr,3 Bedrooms,3 Bathrooms,2 Balconies,May 2026,"Pool,Park/Garden,Club,Main Road,Others",NaN,Semifurnished,"Gurgaon, Sector 106 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,"@ 19,425 per sq.ft.",This 3 bhk apartment is available for sale in ...,Study Room,"['Dwarka Sector 21 Metro Station', 'Dwarka Exp...","['Lift(s)', 'High Ceiling Height', 'Maintenanc...",Carpet Area,"1,148 sqft",3 BHK Flat in Sector 106 Gurgaon,A S REALTY,MRG The Crown

In [14]:
df.isna().sum()

Facing               933
Price                 32
No_Bedroom            32
No_Bathroom           33
No_Balcony            32
Age                   36
Overlooking          806
Corner_Property     4272
Furnishing           448
Address               49
Floor Number          32
Per Sqft              34
Main Description       3
Extra Room             0
Nearby Locations       0
Features               0
AreaType               0
Given Area             0
Property Type          0
Dealer                 0
Society Name           0
dtype: int64

In [15]:
df = df.loc[df['No_Bedroom'].isna() == False]

In [16]:
df.shape

(12447, 21)

In [17]:
df.columns

Index(['Facing', 'Price', 'No_Bedroom', 'No_Bathroom', 'No_Balcony', 'Age',
       'Overlooking', 'Corner_Property', 'Furnishing', 'Address',
       'Floor Number', 'Per Sqft', 'Main Description', 'Extra Room',
       'Nearby Locations', 'Features', 'AreaType', 'Given Area',
       'Property Type', 'Dealer', 'Society Name'],
      dtype='object')

In [18]:
df.isna().sum()

Facing               901
Price                  0
No_Bedroom             0
No_Bathroom            1
No_Balcony             0
Age                    4
Overlooking          774
Corner_Property     4240
Furnishing           416
Address               17
Floor Number           0
Per Sqft               2
Main Description       3
Extra Room             0
Nearby Locations       0
Features               0
AreaType               0
Given Area             0
Property Type          0
Dealer                 0
Society Name           0
dtype: int64

In [19]:
# price column

In [20]:
df['Price'].value_counts()

Price
2.25 Cr      197
2.1 Cr       181
3.5 Cr       180
1.8 Cr       179
2.5 Cr       178
            ...
72.97 Lac      1
79.65 Lac      1
98.65 Lac      1
75.31 Lac      1
84.33 Lac      1
Name: count, Length: 986, dtype: int64

In [21]:
def convert_to_crore(price):
    if 'Cr' in price:
        
        return float(price.replace(' Cr', ''))
    elif 'Lac' in price:
       
        return float(price.replace(' Lac', '')) / 100
    else:
        return price

In [22]:

df['Price_in_Crore'] = df['Price'].apply(convert_to_crore)

In [23]:
df['Price_in_Crore'].value_counts().sum()

np.int64(12447)

In [24]:
df[df['Price_in_Crore'] == 'Price on Request']

,Facing,Price,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Floor Number,Per Sqft,Main Description,Extra Room,Nearby Locations,Features,AreaType,Given Area,Property Type,Dealer,Society Name,Price_in_Crore
6750,North-East,Price on Request,5 Bedrooms,6 Bathrooms,3+ Balconies,1 to 5 Year Old,NaN,NaN,Semifurnished,"Or Sale - Penthouse At Ambience Caitriona, Sec...",11st of 12 Floors,NaN,"Penthouse on sale, Caitriona 7 star living at ...","Pooja Room,Study Room,Servant Room,Others","['Moulsari Avenue Metro Station', 'Phase 3, Cy...","['Power Back-up', 'Intercom Facility', 'Lift(s...",Super Built-up Area,"13,500 sqft","5 BHK Flat in DLF Phase 3, Gurgaon",Sharma Estates,Ambience Caitriona,Price on Request
12640,North-East,Price on Request,4 Bedrooms,7 Bathrooms,3 Balconies,0 to 1 Year Old,"Park/Garden,Club,Pool",NaN,Unfurnished,For Sale - 4 Bhk Luxury Apartment In Dlf The C...,15th of 38 Floors,NaN,This is a ready to move in 4 bhk flat for sale...,"Servant Room,Others,Pooja Room,Study Room","['Sector 42-43 Rapid Metro', 'Sector 53-54 Rap...","['Intercom Facility', 'Lift(s)', 'Feng Shui / ...",Super Built-up Area,"7,430 sqft",4 BHK Flat in Sector 42 Gurgaon,Sharma Estates,DLF The Camellias,Price on Request

In [25]:
df.drop(columns = 'Price' , inplace= True)

In [26]:
df.sample(4)

,Facing,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Floor Number,Per Sqft,Main Description,Extra Room,Nearby Locations,Features,AreaType,Given Area,Property Type,Dealer,Society Name,Price_in_Crore
3755,NaN,3 Bedrooms,3 Bathrooms,3 Balconies,By 2025,NaN,NaN,Semifurnished,"Sector 37D Gurgaon, Gurgaon, Haryana",11st of 39 Floors,"@ 14,487 per sq.ft.",This beautiful 3 bhk flat in sector 37d gurgao...,Study Room,"['The Esplanade Mall', 'Pataudi Road', 'Alpine...","['Power Back-up', 'Swimming Pool', 'Park', 'Sh...",Super Built-up Area,"2,623 sqft",3 BHK Flat in Sector 37D Gurgaon,Property Line,Signature Global De Luxe DXP,3.8
7283,East,3 Bedrooms,4 Bathrooms,3+ Balconies,1 to 5 Year Old,"Main Road,Club,Park/Garden,Pool,Others",Yes,Unfurnished,"Sector 82A Gurgaon, Gurgaon, Haryana",11st of 32 Floors,"@ 12,703 per sq.ft.",Dlf the primus is one of gurgaon's most sought...,No,"['Sapphire 83', 'NH 48', 'Cambridge Montessori...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",Super Built-up Area,"2,086 sqft",3 BHK Flat in Sector 82A Gurgaon,Arihant Real India Group,DLF The Primus,2.65
2366,North-West,3 Bedrooms,3 Bathrooms,3 Balconies,1 to 5 Year Old,"Pool,Park/Garden,Main Road,Club",Yes,Semifurnished,"Sector 67A Gurgaon, Gurgaon, Haryana",9th of 19 Floors,"@ 13,072 per sq.ft.",Its 3bhk with servant room and store room semi...,"Servant Room,Store Room","['Huda Metro Station (Gurugram)', 'Paras Trini...","['Water purifier', 'Security / Fire Alarm', 'F...",Super Built-up Area,"1,920 sqft",3 BHK Flat in Sector 67A Gurgaon,Home Solutions,Ireo The Corridors,2.51
7068,West,3 Bedrooms,3 Bathrooms,3+ Balconies,0 to 1 Year Old,"Main Road,Club,Park/Garden,Pool,Others",Yes,Semifurnished,"3 Ldk, Sector 36A Gurgaon, Gurgaon, Haryana",18th of 34 Floors,"@ 18,471 per sq.ft.","Situated in sector 36a gurgaon, krisumi waterf...",Study Room,"['Sapphire 83', 'Dwarka Expressway', 'Sector 8...","['Water purifier', 'Centrally Air Conditioned'...",Super Built-up Area,"1,976 sqft",3 BHK Flat in Sector 36A Gurgaon,Group 3 Realtors,Krisumi Waterfall Residences,3.65

In [27]:
df[df['Price_in_Crore'] == 0.7].head(3)

,Facing,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Floor Number,Per Sqft,Main Description,Extra Room,Nearby Locations,Features,AreaType,Given Area,Property Type,Dealer,Society Name,Price_in_Crore
1,South,2 Bedrooms,2 Bathrooms,1 Balcony,1 to 5 Year Old,"Others,Park/Garden,Main Road",NaN,Unfurnished,"0001, Sector 90 Gurgaon, Gurgaon, Haryana",8th of 14 Floors,"@ 10,144 per sq.ft.","Green court society, which is bang on 60-Meter...",Store Room,"['Baba Kanala Chowk', 'Pataudi Rd', 'Gurukul P...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",Super Built-up Area,690 sqft,2 BHK Flat in Sector 90 Gurgaon,Ashiana homes,Green Court,0.7
11,South,2 Bedrooms,2 Bathrooms,1 Balcony,1 to 5 Year Old,NaN,NaN,Unfurnished,"Sector 76 Gurgaon, Gurgaon, Haryana",7th of 14 Floors,"@ 1,29,390 per sq.m.",Check out this 2 bhk apartment for sale in sun...,No,"['M3M Corner Walk', 'NH 48', 'Kunskapsskolan I...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",Carpet Area,582 sqft,2 BHK Flat in Sector 76 Gurgaon,Kataria Real Estate,Suncity Avenue 76,0.7
30,North-East,2 Bedrooms,2 Bathrooms,1 Balcony,1 to 5 Year Old,Park/Garden,Yes,Furnished,"907, Sector 70A Gurgaon, Gurgaon, Haryana",10th of 14 Floors,"@ 13,972 per sq.ft.",This beautiful 2 bhk flat in sector 70a gurgao...,No,"['Airia Mall', 'Sohna Road', ""St. Angel's Glob...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",Carpet Area,501 sqft,2 BHK Flat in Sector 70A Gurgaon,Jain Buildwell,Pyramid Urban Homes,0.7

In [28]:
# No.of_bedrooms column

In [29]:
def No_Bedroomss(No_Bedroom):
    if 'Bedrooms' in No_Bedroom:
        
        return int(No_Bedroom.replace(' Bedrooms', ''))
    if 'Bedroom' in No_Bedroom:
        
        return int(No_Bedroom.replace(' Bedroom', ''))
    else:
        return No_Bedroom

In [30]:
df['No_Bedroom'] = df['No_Bedroom'].apply(No_Bedroomss)

In [31]:
df['No_Bedroom'].isnull().sum()

np.int64(0)

In [32]:
df['No_Bedroom'].value_counts()

No_Bedroom
3    6788
4    2904
2    2376
5     247
1     109
6      22
7       1
Name: count, dtype: int64

In [33]:
# No.of_bathrooms column

In [34]:
df['No_Bathroom'].value_counts()

No_Bathroom
3 Bathrooms    4584
4 Bathrooms    3446
2 Bathrooms    2671
5 Bathrooms    1157
6 Bathrooms     377
1 Bathroom      131
7 Bathrooms      65
8 Bathrooms      14
9 Bathrooms       1
Name: count, dtype: int64

In [35]:
def No_Bathroomss(No_Bathroom):

    if isinstance(No_Bathroom, str):
        if 'Bathrooms' in No_Bathroom:
            return int(No_Bathroom.replace(' Bathrooms', '').strip())
        if 'Bathroom' in No_Bathroom:
            return int(No_Bathroom.replace(' Bathroom', '').strip())
        else:
            return No_Bathroom  
    else:
        return No_Bathroom

In [36]:
df['No_Bathroom'] = df['No_Bathroom'].apply(No_Bathroomss)

In [37]:
df['No_Bathroom'].value_counts()

No_Bathroom
3.0    4584
4.0    3446
2.0    2671
5.0    1157
6.0     377
1.0     131
7.0      65
8.0      14
9.0       1
Name: count, dtype: int64

In [38]:
df['No_Bathroom'].isnull().sum()

np.int64(1)

In [39]:
# No.of_Balcony column

In [40]:
df['No_Balcony'].value_counts()

No_Balcony
3+ Balconies    4948
3 Balconies     4354
2 Balconies     2547
1 Balcony        583
No Balcony        15
Name: count, dtype: int64

In [41]:
balcony_mapping = {
    '3+ Balconies': 4,
    '3 Balconies': 3,
    '2 Balconies': 2,
    '1 Balcony': 1,
    'No Balcony': 0
}

df['No_Balcony'] = df['No_Balcony'].map(balcony_mapping)

In [42]:
df['No_Balcony'].isnull().sum()

np.int64(0)

In [43]:
df['No_Balcony'].value_counts()

No_Balcony
4    4948
3    4354
2    2547
1     583
0      15
Name: count, dtype: int64

In [44]:
df.columns

Index(['Facing', 'No_Bedroom', 'No_Bathroom', 'No_Balcony', 'Age',
       'Overlooking', 'Corner_Property', 'Furnishing', 'Address',
       'Floor Number', 'Per Sqft', 'Main Description', 'Extra Room',
       'Nearby Locations', 'Features', 'AreaType', 'Given Area',
       'Property Type', 'Dealer', 'Society Name', 'Price_in_Crore'],
      dtype='object')

In [45]:
# per_sqrt column

In [46]:
df['Per Sqft'].value_counts()

Per Sqft
@ 20,000 per sq.ft.     64
@ 10,000 per sq.ft.     64
@ 12,000 per sq.ft.     57
@ 15,000 per sq.ft.     47
@ 12,500 per sq.ft.     42
                        ..
@ 12,167 per sq.ft.      1
@ 5,052 per sq.ft.       1
@ 1,32,942 per sq.m.     1
@ 23,720 per sq.ft.      1
@ 25,966 per sq.ft.      1
Name: count, Length: 6857, dtype: int64

In [47]:
def price_Per_Sqft(per_sqft):
   
    if isinstance(per_sqft, str):
       
        if '@' in per_sqft:
            return per_sqft.replace('@ ', '').replace(' per', '')
            
    return per_sqft

In [48]:
df['price_Per_Sqft'] = df['Per Sqft'].apply(price_Per_Sqft)

In [49]:
df['price_Per_Sqft'].value_counts()

price_Per_Sqft
20,000 sq.ft.     64
10,000 sq.ft.     64
12,000 sq.ft.     57
15,000 sq.ft.     47
12,500 sq.ft.     42
                  ..
12,167 sq.ft.      1
5,052 sq.ft.       1
1,32,942 sq.m.     1
23,720 sq.ft.      1
25,966 sq.ft.      1
Name: count, Length: 6857, dtype: int64

In [50]:
import re
def extract_number_and_unit(value):

    if isinstance(value, str):
        match = re.match(r'([\d,]+)\s*(\w+\.\w+|\w+)', value)
        if match:
            number = match.group(1).replace(",", "") 
            unit = match.group(2)  
            return pd.Series([number, unit])
    return pd.Series([None, None])

In [51]:
# Apply the function to the 'price_Per_Sqft' column
df[['number', 'unit']] = df['price_Per_Sqft'].apply(extract_number_and_unit)

In [52]:
def extract_number_and_convert(value):
    if isinstance(value, str):
        # Extract numeric part (removing commas) and unit part using regex
        match = re.match(r'([\d,]+)\s*(\w+\.\w+|\w+)', value)
        if match:
            number = float(match.group(1).replace(",", ""))  # Remove commas and convert to float
            
            # Conversion to sq.ft.
            if "sq.m." in value:
                number = number * 10.764
                return number
            elif "sq.yards" in value:
                number = number * 9
                return number
            elif "sq.ft." in value:                         
                return number
    return None

In [53]:
# Apply the function to convert all areas to sq.ft.
df['price_Per_Sqft_converted'] = df['price_Per_Sqft'].apply(extract_number_and_convert)

In [54]:
df[df['unit'] == 'sq.yards']

,Facing,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Floor Number,Per Sqft,Main Description,Extra Room,Nearby Locations,Features,AreaType,Given Area,Property Type,Dealer,Society Name,Price_in_Crore,price_Per_Sqft,number,unit,price_Per_Sqft_converted
214,North-East,2,2.0,1,Within 6 months,"Club,Park/Garden,Pool,Others,Main Road",Yes,NaN,"A10107, Sector 85 Gurgaon, Gurgaon, Haryana",17th of 25 Floors,"@ 18,164 per sq.yards",Godrej air is one of the most popular destinat...,No,"['Millennium City Centre Gurugram', 'Iris Broa...","['Intercom Facility', 'Lift(s)', 'High Ceiling...",Super Built-up Area,"12,834 sqft",2 BHK Flat in Sector 85 Gurgaon,Philby Real Estate,Godrej Air,1.9,"18,164 sq.yards",18164,sq.yards,163476.0
530,East,2,2.0,2,1 to 5 Year Old,"Park/Garden,Main Road",NaN,Semifurnished,"Kenwood, Malibu Town, Gurgaon, Haryana",2nd of 4 Floors,"@ 1,06,000 per sq.yards",A beautiful 2 + study flat available for sale ...,"Pooja Room,Study Room,Servant Room","['Raheja Mall', 'Standard chartered ATM', 'Ici...","['Feng Shui / Vaastu Compliant', 'Security / F...",Carpet Area,"1,800 sqft","2 BHK Flat in Malibu Town, Gurgaon",EarthZ Enterprise solutions pvt ltd,Malibu Towne,2.12,"1,06,000 sq.yards",106000,sq.yards,954000.0
612,North-East,2,2.0,2,1 to 5 Year Old,Park/Garden,Yes,Semifurnished,"Sector 83 Gurgaon, Gurgaon, Haryana",Ground of 2 Floors,"@ 77,777 per sq.yards","Vatika india next emelia floor, ground floor, ...",No,"['New Millennium City Centre Metro', 'Sapphire...","['Feng Shui / Vaastu Compliant', 'Maintenance ...",Carpet Area,"1,620 sqft",2 BHK Flat in Sector 83 Gurgaon,Happy Homes,Vatika India Next Plots,1.4,"77,777 sq.yards",77777,sq.yards,699993.0
613,East,2,2.0,2,1 to 5 Year Old,Park/Garden,NaN,Semifurnished,"Sector 82 Gurgaon, Gurgaon, Haryana",1st of 2 Floors,"@ 66,666 per sq.yards","Vatika india next emelia floor, first floor, p...",No,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...","['Power Back-up', 'Feng Shui / Vaastu Complian...",Carpet Area,"1,620 sqft",2 BHK Flat in Sector 82 Gurgaon,Happy Homes,Vatika Independent Floors,1.2,"66,666 sq.yards",66666,sq.yards,599994.0
1749,East,2,2.0,2,1 to 5 Year Old,"Main Road,Pool,Others,Park/Garden",Yes,Unfurnished,"0000, Sohna, Gurgaon, Haryana",6th of 14 Floors,"@ 9,433 per sq.yards",This 2 bhk apartment is available for sale in ...,No,"['Signature Global Infinity Mall', 'Sohna Road...","['Security / Fire Alarm', 'Lift(s)', 'Water St...",Carpet Area,"5,247 sqft","2 BHK Flat in Sohna, Gurgaon",City Properties,Signature The Serenas,0.55,"9,433 sq.yards",9433,sq.yards,84897.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12128,East,3,3.0,4,1 to 5 Year Old,"Pool,Park/Garden,Club,Main Road,Others",Yes,Semifurnished,"Sector 109 Gurgaon, Gurgaon, Haryana",Ground of 2 Floors,"@ 1,10,833 per sq.yards",International city by sobha phase 2 is one of ...,Servant Room,"['Dwarka Sector 21 Metro Station', 'Pacific D2...","['Water purifier', 'Centrally Air Conditioned'...",Super Built-up Area,"5,400 sqft",3 BHK Flat in Sector 109 Gurgaon,Gupta Realtors,International City by SOBHA Phase 2,6.65,"1,10,833 sq.yards",110833,sq.yards,997497.0
12187,East,3,3.0,3,1 to 5 Year Old,"Park/Garden,Main Road",NaN,Semifurnished,"Ansal Api Esencia, Sector 67 Gurgaon, Gurgaon,...",Ground of 2 Floors,"@ 64,000 per sq.yards",Check out this 3 bhk apartment for sale in ans...,Pooja Room,"['Proposed Metro corridor', 'N.H-8', 'Golf Cou...","['Power Back-up', 'High Ceiling Height', 'Swim...",Carpet Area,"2,250 sqft",3 BHK Flat in Sector 67 Gurgaon,RELIABLE REALTORS,Ansal API Esencia,1.6,"64,000 sq.yards",64000,sq.yards,576000.0
12329,East,3,3.0,2,10+ Year Old,"Park/Garden,Main Road,Others,Club",Yes,Semifurnished,"2 Nd Floor, Sector 57 Gurgaon, Gurgaon, Haryana",2nd of 3 Floors,"@ 57,272 per sq.yards",This 3 bhk apartment is available for sale in ...,Pooja Room,"['Hong Kong Bazaar Mall', 'Radhakrishna Shani ...","['Power Back-up', 'Feng Shui / Vaastu Complian...",Super Built-up Area,"2,970 sqft",3 BHK Flat in Sector 57 Gurgaon,Perfect Homes Realty,M2K The White House,1.89,"57,272 sq.yards",57272,sq.yards,515448.0
12401,North-East,3,3.0,2,5 to 10 Year Old,"Park/Garden,Main Road,Sea facing,Others",Yes,Semifurnished,"2nd Floor, Sector 47 Gurgaon, Gurgaon, Haryana",2nd of 2 Floors,"@ 69,230 per sq.yards",Today blossoms 1 is one of gurgaon's most soug...,Pooja Room,"['Raheja Mall', 'Standard chartered ATM', 'Ici...","['Power Back-up', 'Feng Shui / Vaastu Complian...",Super Built-up Area,"2,556 sqft",3 BHK Flat in Sector 47 Gurgaon,Perfect Homes Realty,Today Blossoms 1,1.8,"69,230 sq.yards",69230,sq.yards,623070.0
13880,East,3,3.0,2,1 to 5 Year Old,"Park/Garden,Main Road,Pool",Yes,Semifurnished,"1231, Sector 102 Gurgaon, Gurgaon, Haryana",Ground of 2 Floors,"@ 99,009 per sq.yards",Looking for a 3 bhk property for sale in gurga...,Study Room,"['Early Basket Grocery shop', 'Conscient One M...","['Water purifier', 'Security / Fire Alarm', 'P...",Carpet Area,"2,727 sqft",3 BHK Flat in Sector 102 Gurgaon,Vinod Associates,BPTP Amstoria,3.0,"99,009 sq.yards",99009,sq.yards,891081.0

In [55]:
df = df.drop(columns= ['price_Per_Sqft' , 'number' , 'unit'])

In [56]:
df.sample(3)

,Facing,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Floor Number,Per Sqft,Main Description,Extra Room,Nearby Locations,Features,AreaType,Given Area,Property Type,Dealer,Society Name,Price_in_Crore,price_Per_Sqft_converted
1991,North-East,3,3.0,2,10+ Year Old,Others,Yes,Furnished,"DLF Phase 4, Gurgaon, Haryana",7th of 21 Floors,"@ 19,696 per sq.ft.",Regency park 2 is one of gurgaon's most sought...,Servant Room,"['Dlf phase 1 metro station', 'Sector 42-43 me...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",Super Built-up Area,"1,777 sqft","3 BHK Flat in DLF Phase 4, Gurgaon",Vishva Karma Associates,DLF Regency Park 2,3.5,19696.0
10328,East,3,3.0,2,1 to 5 Year Old,"Main Road,Club,Park/Garden,Pool",Yes,Semifurnished,"Sector 37D Gurgaon, Gurgaon, Haryana",10th of 23 Floors,"@ 11,720 per sq.ft.",Looking for a 3 bhk property for sale in gurga...,Servant Room,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",Super Built-up Area,"1,877 sqft",3 BHK Flat in Sector 37D Gurgaon,INFRAMANTRA INDIA PRIVATE LIMITED,BPTP Terra,2.2,11720.0
5671,NaN,3,4.0,3,1 to 5 Year Old,NaN,NaN,Semifurnished,"Sector 71 Gurgaon, Gurgaon, Haryana",3rd of 14 Floors,"@ 9,544 per sq.ft.","Situated in sector 71 gurgaon, chd avenue 71 i...",Servant Room,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",Carpet Area,"1,802 sqft",3 BHK Flat in Sector 71 Gurgaon,Individual Consultant,CHD Avenue 71,1.72,9544.0

In [57]:
#Given area

In [58]:
df['Given Area'].value_counts()

Given Area
2,400 sqft    202
1,950 sqft    136
1,650 sqft    128
2,150 sqft    124
2,000 sqft    103
             ...
320 sqft        1
1,412 sqft      1
1,763 sqft      1
1,766 sqft      1
2,910 sqft      1
Name: count, Length: 1580, dtype: int64

In [59]:
df[['number', 'unit']] = df['Given Area'].apply(extract_number_and_unit)

In [60]:
df['unit'].value_counts()

unit
sqft    12447
Name: count, dtype: int64

In [61]:
df = df.drop(columns= ['unit'])

In [62]:
df.rename(columns={'number': 'given_area_in_sqft'}, inplace=True)

In [63]:
df = df.drop(columns= ['Given Area'])

In [64]:
df.sample(7)

,Facing,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Floor Number,Per Sqft,Main Description,Extra Room,Nearby Locations,Features,AreaType,Property Type,Dealer,Society Name,Price_in_Crore,price_Per_Sqft_converted,given_area_in_sqft
2154,East,3,3.0,4,1 to 5 Year Old,"Sea facing,Main Road,Park/Garden,Others,Club,Pool",Yes,Semifurnished,"123, Sector 81 Gurgaon, Gurgaon, Haryana",18th of 29 Floors,"@ 16,880 per sq.ft.","This 3 bhk flat is located in dlf the ultima, ...",Servant Room,"['Huda Metro Station (Gurugram)', 'Vatika Town...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",Super Built-up Area,3 BHK Flat in Sector 81 Gurgaon,JSK Realtors,DLF The Ultima,3.55,16880.0,2103
6042,East,3,2.0,3,0 to 1 Year Old,"Pool,Others,Park/Garden,Club,Main Road",Yes,Unfurnished,"Sector 68 Gurgaon, Gurgaon, Haryana",2nd of 35 Floors,"@ 12,002 per sq.ft.","Check out pareena mi casa in sector 68, one of...",No,"['Sector 55-56 Metro Station', 'Airia Mall', '...","['Centrally Air Conditioned', 'Water purifier'...",Super Built-up Area,3 BHK Flat in Sector 68 Gurgaon,Gurgaon Realtors,Pareena Mi Casa,1.78,12002.0,1483
148,West,2,2.0,3,0 to 1 Year Old,"Park/Garden,Club,Others,Main Road,Sea facing",Yes,Semifurnished,"Sector 89 A Gurgaon, Gurgaon, Haryana",8th of 21 Floors,"@ 10,300 per sq.ft.",Vatika seven elements is one of the most popul...,Servant Room,"['Millennium City Centre Gurugram', 'Newtown S...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",Super Built-up Area,2 BHK Flat in Sector 89 A Gurgaon,Right Realtors,Vatika Seven Elements,1.69,10300.0,1645
1120,NaN,2,2.0,3,0 to 1 Year Old,NaN,NaN,NaN,"Sohna, Gurgaon, Haryana",2nd of 4 Floors,"@ 9,732 per sq.ft.","Location , connectivity = nera to hospital, ne...",No,"['Airia Mall', 'NH248A', 'K. R. Mangalam Unive...","['Lift(s)', 'Swimming Pool', 'Fitness Centre /...",Carpet Area,"2 BHK Flat in Sohna, Gurgaon",Instagrow Investments,Signature Global Park,0.8,9732.0,822
3318,South-West,4,4.0,4,10+ Year Old,"Park/Garden,Pool,Main Road,Sea facing,Club,Others",Yes,Semifurnished,"123, DLF Phase 2, Gurgaon, Haryana",4th of 19 Floors,"@ 17,817 per sq.ft.","This beautiful 4 bhk flat in dlf phase 2, gurg...",Servant Room,"['Vodafone belvedere towers metro station', 'D...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",Super Built-up Area,"4 BHK Flat in DLF Phase 2, Gurgaon",Gurgaon Homes,DLF Belvedere Towers,4.0,17817.0,2245
13219,East,2,2.0,3,1 to 5 Year Old,"Pool,Park/Garden,Club,Others,Main Road,Sea facing",Yes,Semifurnished,"Sector 103 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,"@ 9,135 per sq.ft.",Check out this 2 bhk apartment for sale in ind...,Study Room,"['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",Super Built-up Area,2 BHK Flat in Sector 103 Gurgaon,bhoomi,Indiabulls Centrum Park,1.3,9135.0,1423
7238,North-West,4,4.0,3,5 to 10 Year Old,Park/Garden,NaN,Semifurnished,"Sector 54 Gurgaon, Gurgaon, Haryana",12nd of 30 Floors,"@ 24,255 per sq.ft.",Dlf park place is one of the most popular dest...,Servant Room,"['Sector 53-54 Metro Station', 'Sector 54 Chow...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",Super Built-up Area,4 BHK Flat in Sector 54 Gurgaon,Khushal Sethi Housing Solutions Pvt. Ltd.,DLF Park Place,8.25,24255.0,2721

In [65]:
df['Floor Number'].value_counts()

Floor Number
2nd   of 4 Floors        271
7th   of 14 Floors       195
8th   of 14 Floors       192
1st   of 4 Floors        178
3rd   of 4 Floors        165
                        ...
23rd   of 33 Floors        1
18th   of 41 Floors        1
4th   of 34 Floors         1
Basement of 25 Floors      1
17th   of 37 Floors        1
Name: count, Length: 926, dtype: int64

In [66]:
def extract_floors(value):
    try:

        patterns = [
            r'(\d+)[a-z]{2}\s+of\s+(\d+)',  
            r'(\d+)\s+of\s+(\d+)',         
            r'(Ground|Basement|Lower Ground|Upper Ground)\s+of\s+(\d+)' 
        ]
        
        for pattern in patterns:
            match = re.search(pattern, value, re.IGNORECASE)
            if match:
                floor_number = match.group(1)
                
                # Handle specific cases
                if floor_number.lower() == "ground":
                    floor_number = 0
                elif floor_number.lower() == "lower ground":
                    floor_number = -1
                elif floor_number.lower() == "basement":
                    floor_number = -2
                elif floor_number.isdigit():
                    floor_number = int(floor_number)
                
                total_floors = int(match.group(2))
                
                return floor_number, total_floors

        return value, value
    except Exception:

        return value, value

df[['floor_number', 'total_floors']] = df['Floor Number'].apply(lambda x: pd.Series(extract_floors(x)))

In [67]:
df.sample(5)

,Facing,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Floor Number,Per Sqft,Main Description,Extra Room,Nearby Locations,Features,AreaType,Property Type,Dealer,Society Name,Price_in_Crore,price_Per_Sqft_converted,given_area_in_sqft,floor_number,total_floors
11538,North-East,3,3.0,3,Feb 2025,"Park/Garden,Main Road,Club,Pool",Yes,Semifurnished,"Sector 76 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,"@ 14,923 per sq.ft.",Looking for a 3 bhk property for sale in gurga...,"Pooja Room,Study Room,Servant Room","['Vatika Town Square-INXT', 'NH 48', 'Vega Sch...","['Feng Shui / Vaastu Compliant', 'Security / F...",Super Built-up Area,3 BHK Flat in Sector 76 Gurgaon,DREAM TOWN REALTY,Whiteland Blissville,1.94,14923.0,1672,2,4
3090,North-East,3,3.0,2,1 to 5 Year Old,"Pool,Others,Park/Garden,Club,Main Road",Yes,Semifurnished,"6576, Sector 108 Gurgaon, Gurgaon, Haryana",14th of 24 Floors,"@ 15,040 per sq.ft.",This lovely 2 bhk apartment/flat in sector 108...,No,"['Dwarka Sector 21 Metro Station', 'WTC Plaza'...","['Centrally Air Conditioned', 'Water purifier'...",Super Built-up Area,3 BHK Flat in Sector 108 Gurgaon,FLAG SQUARE,Sobha City,3.38,15040.0,2343,14,24
9475,North-East,4,5.0,2,5 to 10 Year Old,"Pool,Park/Garden,Club,Main Road,Others",Yes,Unfurnished,"Sector 81 Gurgaon, Gurgaon, Haryana",16th of 19 Floors,"@ 11,930 per sq.ft.","Situated in sector 81 gurgaon, bestech park vi...",Servant Room,"['Sapphire 83 Mall', 'NH-8, IMT Manesar', 'Dwa...","['Centrally Air Conditioned', 'Security / Fire...",Super Built-up Area,4 BHK Flat in Sector 81 Gurgaon,SHARMA ESTATE,Bestech Park View Grand Spa,3.8,11930.0,3185,16,19
7183,East,4,4.0,4,Feb 2026,"Pool,Park/Garden,Club,Main Road,Others",Yes,Unfurnished,"Sector 113 Gurgaon , Gurgaon, Haryana",7th of 36 Floors,"@ 15,752 per sq.ft.",This 4 bhk apartment is available for sale in ...,"Study Room,Servant Room","['Phase 2 Metro Station', 'Global Foyer Mall',...","['Power Back-up', 'Security / Fire Alarm', 'Li...",Carpet Area,4 BHK Flat in Sector 113 Gurgaon,JBM Buildtech Pvt Ltd,M3M Capital,3.62,15752.0,2298,7,36
313,North-East,2,2.0,4,1 to 5 Year Old,"Main Road,Park/Garden",NaN,Unfurnished,"Sector 106 Gurgaon, Gurgaon, Haryana",5th of 24 Floors,"@ 9,747 per sq.ft.",Dwarka expressway is the new growth corridor o...,No,"['MG Road Metro Station', 'NeoSquare Shopping ...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",Super Built-up Area,2 BHK Flat in Sector 106 Gurgaon,Satyam Estates,Paras Dews,1.35,9747.0,1385,5,24

In [68]:
df['total_floors'].isna().sum()

np.int64(0)

In [69]:
df = df.drop(columns= ['Floor Number'])

In [70]:
df = df.drop(columns= ['Per Sqft'])

In [71]:
df.sample(6)

,Facing,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Main Description,Extra Room,Nearby Locations,Features,AreaType,Property Type,Dealer,Society Name,Price_in_Crore,price_Per_Sqft_converted,given_area_in_sqft,floor_number,total_floors
5472,NaN,6,7.0,3,1 to 5 Year Old,NaN,NaN,Unfurnished,"Sector 42 Gurgaon, Gurgaon, Haryana",Dlf the camellias is a prestigious ultra-Luxur...,"Servant Room,Pooja Room","['Sector 42-43 Rapid Metro', 'Sector 53-54 Rap...","['Power Back-up', 'Feng Shui / Vaastu Complian...",Super Built-up Area,6 BHK Flat in Sector 42 Gurgaon,Earth Ved Associates,DLF The Camellias,85.0,77272.0,11000,17,38
5797,East,3,3.0,4,1 to 5 Year Old,"Main Road,Club,Park/Garden,Pool,Others",Yes,Semifurnished,"Sector 37D Gurgaon, Gurgaon, Haryana","Situated in sector 37d gurgaon, ramprastha the...",No,"['The Esplanade Mall', 'Dwarka Express', 'Euro...","['Centrally Air Conditioned', 'Water purifier'...",Super Built-up Area,3 BHK Flat in Sector 37D Gurgaon,Rawat Properties,Ramprastha The Edge Towers,1.35,7627.0,1770,10,19
676,North-East,2,2.0,1,1 to 5 Year Old,"Main Road,Park/Garden,Club",Yes,Unfurnished,"1111111, Sector 102 Gurgaon, Gurgaon, Haryana",Suncity avenue 102 is one of the most popular ...,No,"['The Esplanade Mall', 'Dwarka Expressway', 'I...","['Water purifier', 'Security / Fire Alarm', 'F...",Super Built-up Area,2 BHK Flat in Sector 102 Gurgaon,Vinod Associates,Suncity Avenue 102,0.65,10734.0,605,12,12
6250,East,4,4.0,3,1 to 5 Year Old,"Pool,Park/Garden,Club,Main Road",Yes,Semifurnished,"1502, Sector 72 Gurgaon, Gurgaon, Haryana","Luxurious 4 bhk + sq at tata primanti, sector ...","Servant Room,Pooja Room","['Sector 55-56 Metro Station', 'Omaxe City Cen...","['Centrally Air Conditioned', 'Water purifier'...",Super Built-up Area,4 BHK Flat in Sector 72 Gurgaon,Oxford Realtors,Tata Primanti,6.85,20417.0,3355,15,38
2579,South,4,6.0,4,5 to 10 Year Old,"Park/Garden,Pool,Main Road,Sea facing,Club,Others",Yes,Semifurnished,"C-1300, Sector 47 Gurgaon, Gurgaon, Haryana",This 4 bhk flat is located in bestech park vie...,"Pooja Room,Servant Room","['Hong Kong Bazaar', 'Golf Course Ext Rd', 'Am...","['Feng Shui / Vaastu Compliant', 'Security / F...",Super Built-up Area,4 BHK Flat in Sector 47 Gurgaon,Nimantran Homes,Bestech Park View Spa,6.75,21600.0,3125,13,18
5286,East,3,4.0,4,Jul 2027,"Club,Park/Garden",NaN,Semifurnished,"2703, Sector 61 Gurgaon, Gurgaon, Haryana","Excellent location , 3 bhk, middle floor apart...",Servant Room,"['Sector 54 Chowk', 'Central Plaza Mall', 'Nat...","['Centrally Air Conditioned', 'Water purifier'...",Super Built-up Area,3 BHK Flat in Sector 61 Gurgaon,Jain Consultancy Services,Puri The Aravallis,4.05,18000.0,2250,27,42

In [72]:
# AreaType

In [73]:
df['AreaType'].value_counts()

AreaType
Super Built-up Area    9956
Carpet Area            1848
Built-up Area           643
Name: count, dtype: int64

In [74]:
df = pd.get_dummies(df, columns=['AreaType'], prefix='AreaType')

In [75]:
df.sample(6)

,Facing,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Main Description,Extra Room,Nearby Locations,Features,Property Type,Dealer,Society Name,Price_in_Crore,price_Per_Sqft_converted,given_area_in_sqft,floor_number,total_floors,AreaType_Built-up Area,AreaType_Carpet Area,AreaType_Super Built-up Area
9227,NaN,3,4.0,4,By 2026,NaN,NaN,Semifurnished,"Sector 76 Gurgaon, Gurgaon, Haryana",Check out this 3 bhk apartment for sale in whi...,Servant Room,"['Sapphire 83 Mall', 'National Highway 48', 'V...","['Lift(s)', 'Park', 'Club house / Community Ce...",3 BHK Flat in Sector 76 Gurgaon,Vishwas Associates,Whiteland The Aspen,3.09,13500.0,2290,15,42,False,False,True
1187,South,2,2.0,3,Within 6 months,"Main Road,Park/Garden",Yes,Semifurnished,"Tower 2, Sector 85 Gurgaon, Gurgaon, Haryana","This 2 bhk flat is located in godrej air, whic...",Pooja Room,"['Millennium City Centre Gurugram', 'Iris Broa...","['Water purifier', 'Centrally Air Conditioned'...",2 BHK Flat in Sector 85 Gurgaon,Eternity Home Exchange,Godrej Air,1.8,12802.0,1406,9,32,False,False,True
10885,East,3,3.0,2,Within 3 months,"Park/Garden,Club,Main Road,Others,Pool",Yes,Unfurnished,"Sector 69 Gurgaon, Gurgaon, Haryana","This 3 bhk flat is located in tulip yellow, wh...",No,"['Sector 55-56 Metro Station', 'Airia Mall', '...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",3 BHK Flat in Sector 69 Gurgaon,TAMEDA REALTY,Tulip Yellow,2.1,12323.0,1704,5,26,False,True,False
11078,East,3,3.0,3,May 2025,"Pool,Park/Garden,Main Road,Club",NaN,Semifurnished,"Anaika, Sector 63A Gurgaon, Gurgaon, Haryana",This 3 bhk apartment is available for sale in ...,Servant Room,"['Sector 54 Chowk Metro Station', 'WorldMark G...","['Water purifier', 'Centrally Air Conditioned'...",3 BHK Flat in Sector 63A Gurgaon,Eternity Home Exchange,Birla Navya,3.75,22670.0,1655,2,4,False,True,False
11908,North-East,3,3.0,4,5 to 10 Year Old,"Pool,Park/Garden,Club,Main Road,Others",NaN,Semifurnished,"Tower, Sector 62 Gurgaon, Gurgaon, Haryana",Pioneer urban presidia in sector 62 gurgaon is...,Servant Room,"['Airia Mall', 'Golf Course Ext Road', 'Herita...","['Centrally Air Conditioned', 'Water purifier'...",3 BHK Flat in Sector 62 Gurgaon,Oakfield Realty Private Limited,Pioneer Urban Presidia,6.43,21469.0,2995,17,27,False,False,True
1914,North,2,1.0,1,10+ Year Old,Main Road,NaN,Semifurnished,"Near Cyber City, Udyog Vihar, Nh48, Sector 56 ...",This 2 bedroom set with 1 bathroom balcony att...,No,"['Sector 54 chowk metro station', 'Sector metr...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",2 BHK Flat in Sector 56 Gurgaon,Sahara Properties,Smriti Apartment,0.52,8000.0,650,3,5,False,False,True

In [76]:
df[['AreaType_Built-up Area' , 'AreaType_Carpet Area' , 'AreaType_Super Built-up Area']] = df[['AreaType_Built-up Area' , 'AreaType_Carpet Area' , 'AreaType_Super Built-up Area']].replace({True: 1, False: 0})

C:\Users\dell\AppData\Local\Temp\ipykernel_14892\2151453588.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['AreaType_Built-up Area' , 'AreaType_Carpet Area' , 'AreaType_Super Built-up Area']] = df[['AreaType_Built-up Area' , 'AreaType_Carpet Area' , 'AreaType_Super Built-up Area']].replace({True: 1, False: 0})

In [77]:
df.head()

,Facing,No_Bedroom,No_Bathroom,No_Balcony,Age,Overlooking,Corner_Property,Furnishing,Address,Main Description,Extra Room,Nearby Locations,Features,Property Type,Dealer,Society Name,Price_in_Crore,price_Per_Sqft_converted,given_area_in_sqft,floor_number,total_floors,AreaType_Built-up Area,AreaType_Carpet Area,AreaType_Super Built-up Area
0,West,2,2.0,1,1 to 5 Year Old,"Others,Park/Garden,Main Road",NaN,Unfurnished,"0001, Sector 90 Gurgaon, Gurgaon, Haryana","Green court society, which is bang on 60-Meter...",Store Room,"['Baba Kanala Chowk', 'Pataudi Rd', 'Gurukul P...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",2 BHK Flat in Sector 90 Gurgaon,Ashiana homes,Green Court,0.61,8840.0,690,14,14,0,0,1
1,South,2,2.0,1,1 to 5 Year Old,"Others,Park/Garden,Main Road",NaN,Unfurnished,"0001, Sector 90 Gurgaon, Gurgaon, Haryana","Green court society, which is bang on 60-Meter...",Store Room,"['Baba Kanala Chowk', 'Pataudi Rd', 'Gurukul P...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",2 BHK Flat in Sector 90 Gurgaon,Ashiana homes,Green Court,0.7,10144.0,690,8,14,0,0,1
2,North-East,2,2.0,1,1 to 5 Year Old,"Park/Garden,Club,Main Road",Yes,Semifurnished,"Sector 70A Gurgaon, Gurgaon, Haryana",Available for sale 2 bhk semi furnished in pyr...,No,"['Airia Mall', 'Sohna Road', ""St. Angel's Glob...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",2 BHK Flat in Sector 70A Gurgaon,dbn group,Pyramid Urban Homes,0.71,8492.0,836,9,17,0,0,1
3,East,2,2.0,2,0 to 1 Year Old,"Pool,Park/Garden,Club,Main Road",Yes,Semifurnished,"Sector 68 Gurgaon, Gurgaon, Haryana",Looking for a 2 bhk property for sale in gurga...,No,"['Airia Mall', 'Southern Peripheral Road', 'So...","['Power Back-up', 'Security / Fire Alarm', 'In...",2 BHK Flat in Sector 68 Gurgaon,Shree Shyam Properties,M3M The Marina,1.55,12301.0,1260,9,20,0,0,1
4,North,2,2.0,4,1 to 5 Year Old,"Pool,Club,Park/Garden",Yes,NaN,"101, Sector 107 Gurgaon, Gurgaon, Haryana",This 2 bhk apartment is available for sale in ...,No,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...","['Power Back-up', 'Intercom Facility', 'Lift(s...",2 BHK Flat in Sector 107 Gurgaon,JBM Buildtech Pvt Ltd,M3M Woodshire,1.3,9516.0,1366,1,14,0,0,1

In [78]:
df.to_csv("Cleaned_data_v1.csv")